### ISSUE TITLE
Change ClientInterface::DEFAULT_ENDPOINT for PUBLIC_CLOUD_ENDPOINT 

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-client-php#76] opened 2019-10-25 21:35 UTC
Changing `ClientInterface::DEFAULT_ENDPOINT` for `ClientInterface::PUBLIC_CLOUD_ENDPOINT` should make things more clear since there isn't a default endpoint anymore.
This would involve deprecating `ClientInterface::DEFAULT_ENDPOINT` in favor of the new `ClientInterface::PUBLIC_CLOUD_ENDPOINT`.

**Comment by arunz6161** [comment] 2019-12-10 19:20
Since this a breaking change, we will consider this during next major version.

**Comment by cnovak** [comment] 2020-01-06 19:50
TODO: Make sure to double check the naming of "hybrid" and "public cloud", since the names `SAAS_NG` and `CLASSIC` may be better naming convention, depending on how the marketing/product naming comes out.

**Comment by cnovak** [comment] 2020-12-03 22:54
Duplicate of #112

**Closed as completed by cnovak** 2020-12-03 22:54 UTC
Labels: postponed
