### ISSUE TITLE
The `keepOriginalStartDate` attribute is not always set on rate plan revisions.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-client-php#47] opened 2019-03-23 00:04 UTC
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 2.0.1

#### Actual Behavior
Serializing a rate plan revision without `keepOriginalStartDate` set causes an error.

`Property "keepOriginalStartDate" has not been initialized on instance of Apigee\Edge\Api\Monetization\Entity\StandardRatePlanRevision class. Expected type: "boolean".`

#### Expected Behavior

Serializing a pate plan what was retrieved from the API via the client should not error.

#### Steps to Reproduce the behavior

- First, a rate plan revision that doesn't have the keepOriginalStartDate attribute set to true or false.
- Load the rate plan revision.
- Try to serialize the revision.

Subscribe to a rate plan A, cancel it and then subscribe to a plan A again you should get the error.

#### Proposed Solution

Only return true if keepOriginalStartDate is explicitly set to TRUE.

**Comment by Jaesin** [comment] 2019-03-23 00:08
This just checks whether the start date is true in `isKeepOriginalStartDate` as opposed to returning the property directly. [keep-original-start-date.patch.txt](https://github.com/apigee/apigee-client-php/files/2998801/keep-original-start-date.patch.txt)

**Comment by mxr576** [comment] 2019-03-26 09:26
According to the [official API documentation](https://docs.apigee.com/api-platform/monetization/create-future-rate-plans) the `keepOriginalStartDate` property should be always a boolean value in every API responses because if it has not been provided in an API request it falls back to "false".

I did my own quick testing with Postman and as I can see even if the "keepOriginalStartDate" is not being sent to the API, it returns that property with a "false" value as it should.

![image](https://user-images.githubusercontent.com/1755573/54985489-30520c80-4fb1-11e9-9035-f60eb6b83c81.png)

Could you provide some sample raw API calls with API responses to confirm the API may not always return the `keepOriginalStartDate` property in an API response for a rate plan revision?

**Comment by minnur** [comment] 2019-03-26 17:04
@mxr576 the issue is happening to both developers and the teams and it is happening only to revisions. For instance if you subscribe to a rate plan A and cancel it and then subscribe again to a rate plan A you get the error.

I see that the keepOriginalStartDate is getting reset here `https://github.com/apigee/apigee-client-php/blob/002c5fc361200dfb677b75de4d406fdfccefc459/tests/Api/Monetization/EntitySerializer/RatePlanSerializerValidator.php#L76` however returned value in `isKeepOriginalStartDate()` has to be a boolean `src/Api/Monetization/Entity/Property/KeepOriginalStartDatePropertyAwareTrait.php`. Since the normalizer unsetting it we get the error.

For some reason `keepOriginalStartDate = null` in the `previousRatePlanRevision` is playing role in this issue.

![Screen Shot 2019-03-26 at 10 21 55 AM](https://user-images.githubusercontent.com/4031934/55019092-6e4f3080-4fb1-11e9-8e7d-951a6c582ca0.png)

**Comment by mxr576** [comment] 2019-03-27 10:16
What RatePlanSerializerValidator does seems to be unrelated to this problem.

Thanks for the xDebug screenshot. Although I expected some raw JSON API payloads returned by the API and captured by the [Apigee Edge: Debug module](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs) in Drupal after our conversation in private. (Captured response body size has to be increased manually for debugging MINT API calls at this moment: https://github.com/apigee/apigee-edge-drupal/issues/168)

Luckily the screenshot that you attached was enough for me to figure out the test organization and I also have access to that org ;) I used that org for testing too.

So I performed several tests, both in Drupal (by installing the latest MINT module _without_ applying your patch in #48) and on the MGMT UI.

Examining API responses on the MGMT UI with Chrome's network inspector I did not find any other future rate plan that would have a missing `keepOriginalStartDate` property _except_ the one that you have reported as problematic.

![future_rateplan_with_keep_original_start_date](https://user-images.githubusercontent.com/1755573/55067319-c9e7ef80-507f-11e9-8368-fafe00d2733b.png)

I could also successfully subscribe to several (future) rate plans from this organization with a new test developer account in Drupal, except the one that you reported as problematic.

![image](https://user-images.githubusercontent.com/1755573/55066937-1a128200-507f-11e9-95cd-feb28026e02b.png)

@minnur Do you have any other future rate plan on this or _another organization_ that you can reproduce this bug?

Based on this investigation I would dare to say, it could happen the future rate plan that causes this trouble on this organization is stored malformed in the MINT API's database. I remember I created most of these test rate plans on this organization and I tried to "hack" to Monetization API while I was reverse engineered it so I could build the integration for this API in this library.

This also explains why I could not reproduce this issue on my other test organization by creating rate plans on the MGMT UI or with raw API calls in Postman (without trying to hack the API :see_no_evil: ). 

I created my own fix for this problem in #49, but I do not want to merge that PR until you or a customer can confirm that it could happen the "keepOriginalStartDate" property is missing from a future rate plan IF someone did not try to hack the API.

**Comment by cnovak** [comment] 2019-03-27 19:34
The keepOriginalStartDate property is not coming back properly from the this library even when Apigee Edge is returning it, so it should be fixed even if we cannot find another org w/this situation since it can happen. Can we pick one of the fixes and put it in for our next release?

**Comment by mxr576** [comment] 2019-03-28 07:31
> The keepOriginalStartDate property is not coming back properly from this library even when Apigee Edge is returning it

@cnovak Can you provide me a JSON payload that confirms this is what happens or a step by step guides how to reproduce this bug in that test org that we use or any other? Because this was not the problem that @minnur reported and I investigated for this issue.

That bug was about a future rate plan that not even Apigee Edge returns `keepOriginalStartDate` inside its `parentRatePlan` property - however, it should - therefore the PHP API client fails to transforms a `null` (missing property value) to a boolean value.

I performed several tests regarding this problem on the test org that @minnur also uses as you can see above. I even installed the MINT module to try to replicate this bug, but I could only reproduce it with one rate plan. I explained above I created that rate plan and maybe I created it in a way that broke something in the API while I was tried to figure out the API's limitations (to be able to build this API client.)

As you can see, the fix for this bug is a one-liner (plus some comments). I would happily merge it if I would be 100% sure that we are fixing a real bug and not something that is caused by an error on the API side. 

I sent you an invite for a call to debug this issue together.

**Comment by cnovak** [comment] 2019-05-09 19:34
Closing due to PR being closed

**Closed as completed by cnovak** 2019-05-09 19:34 UTC
Labels: bug, tbd
